### PR TITLE
fix(pinia-orm): proper exports for collection and uid helpers

### LINKED ISSUE #1680: Module resolution failure for collection and uid helpers
### Environment

- OS: Windows 10
- Node.js: v18.17.1
- TypeScript: v5.2.2
- Package Manager: Yarn v3.6.3
- Bundler: Vite v4.4.9
- IDE: PhpStorm 2023.2.1

### Reproduction

-

### Describe the bug

Neither TypeScript nor IDE cannot resolve collection/uid helpers:
```
error TS2307: Cannot find module 'pinia-orm/dist/helpers' or its corresponding type declarations.

87 import { useCollect } from "pinia-orm/dist/helpers";
```
Rollup is fine though.

In previous versions of Pinia ORM I just added `.js` at the end and it worked. With `1.7.0` release this hack stopped working for some reason.

### Additional context

My `tsconfig.json`:
```json
{
    "compilerOptions": {
        "allowJs": true,
        "module": "ESNext",
        "moduleResolution": "bundler",
        "jsx": "preserve",
        "strict": true,
        "isolatedModules": true,
        "target": "ESNext",
        "esModuleInterop": true,
        "resolveJsonModule": true,
        "experimentalDecorators": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "skipLibCheck": true,
        "paths": {
            "@/*": ["./resources/js/*"]
        }
    },
    "include": [
        "resources/js/**/*.ts",
        "resources/js/**/*.d.ts",
        "resources/js/**/*.vue",
        "vite.config.ts"
    ]
}
```

### Logs

_No response_

### PR DESCRIPTION
**Pull request by daniser**
### 🔗 Linked issue

#1680

### ❓ Type of change

- [x] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #1680.
All imports are now possible without specifying `dist` folder.
For those who used `dist` and it worked for them - it should still work too (I _think_).
Docs updated accordingly (all `dist` references removed).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by daniser** [comment]
> For those who used `dist` and it worked for them - it should still work too (I _think_).

So, I was wrong about that. Rollup has failed when I tried to import helpers the "old way" (with `dist`).
To preserve BC, we can add safeguard like this (and remove it in v2.0):
```json
"./dist/*": {
  "types": "./dist/*.d.ts",
  "require": "./dist/*.cjs",
  "import": "./dist/*.mjs"
},
"./*": {
  "types": "./dist/*.d.ts",
  "require": "./dist/*.cjs",
  "import": "./dist/*.mjs"
}
```
WDYT?

**Comment by CodeDredd** [comment]
yes i think the same

**Comment by CodeDredd** [comment]
> > also types dont work without "dist" correctly
> 
> That's weird. Modern versions of TS know how to parse `exports` section of `package.json`. What version of TypeScript and which module resolution strategy do you use?

I am using TS 5.2.2 and "moduleResolution": "node". So all fine.
I still remember that i spent hours when i made this package why typscript can't resovle the aliases. I don't know why. I just know that 'dist' works.

**Comment by daniser** [comment]
> I am using TS 5.2.2 and "moduleResolution": "node". So all fine. I still remember that i spent hours when i made this package why typscript can't resovle the aliases. I don't know why. I just know that 'dist' works.
> 
> I think i have to create the folders with an index.ts file like "decorators/index" in the root. I think that then it will work.

FYI: I found out that it's most likely `node` strategy which is [outdated and shouldn't be used in modern code](https://www.typescriptlang.org/tsconfig#moduleResolution). I actually tested it in my project. `node16/nodenext/bundler` worked fine, but when I changed `moduleResolution` to `node`, types stopped working.

Your idea with folders sounds fine if Pinia ORM _really_ need to support legacy versions of Node... which I think doesn't suported currently anyway.

**Pull request merged**
