### PR TITLE
fix: update vue 2 reactivity

### PR DESCRIPTION
**Pull request by Graphmaxer**
### 🔗 Linked issue

https://github.com/CodeDredd/pinia-orm/issues/1772

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

When updating an object in Vue 2, we cannot use directly `Object.assign` with 2 params and `delete` is not reactive.

cf. https://v2.vuejs.org/v2/guide/reactivity.html#For-Objects

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Graphmaxer** [comment]
I don't know how to have 100% of code coverage with Vue 2 conditions, maybe it's possible to combine multiple reports with `nyc` https://github.com/istanbuljs/nyc?tab=readme-ov-file#combining-reports-from-multiple-runs

**Comment by CodeDredd** [comment]
@Graphmaxer Thanks for the PR. I try to look into it and think about it.
I don't like it to have a new package as dependency. I hopefully find a solution to your problem. 
Meanwhile it would be good if could write a test for this.

**Comment by Graphmaxer** [comment]
I updated the test `performance/prevent_rerender_of_child_components` to be compatible with Vue 2 and it is failing because of a lack of reactivity. This test is already testing the bug.

**Comment by Graphmaxer** [comment]
I found a proper way without `vue-demi` as a direct dependency and added a specific tests to test reactivity and it is working great :)

**Comment by phillipfickl** [comment]
Thanks for your PR, it works well for me, reactivity is working again! Tested on 2.7.16.

**Comment by Graphmaxer** [comment]
Any update on the review @CodeDredd ?

**Pull request merged**
